# Generated by Django 3.2.5 on 2021-08-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(default=True, max_length=5)),
                ('balance', models.IntegerField(null=True)),
                ('one_time_pickup', models.DateField(default=django.utils.timezone.now, null=True)),
                ('suspend_start', models.DateField(default=django.utils.timezone.now, null=True)),
                ('suspend_end', models.DateField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
