# Generated by Django 3.2.5 on 2021-08-28 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
