# Generated by Django 3.2.5 on 2021-08-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_weekly_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekly_pickup',
        ),
    ]
