# Generated by Django 3.2.5 on 2021-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210828_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
