# Generated by Django 3.2.5 on 2021-08-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_weekly_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='weekly_pickup',
        ),
    ]
